if Code.ensure_loaded?(SandboxRegistry) do
  defmodule AWS.IAM.Sandbox do
    use AWS.Sandbox,
      registry: :aws_iam_sandbox,
      operations: [
        create_user: [:name],
        get_user: [:name],
        list_users: [],
        delete_user: [:name],
        create_access_key: [:username],
        list_access_keys: [:username],
        delete_access_key: [:key_id, :username],
        create_group: [:name],
        list_groups: [],
        delete_group: [:name],
        add_user_to_group: [:group, :user],
        remove_user_from_group: [:group, :user],
        create_role: [:name],
        get_role: [:name],
        list_roles: [],
        delete_role: [:name],
        create_policy: [:name],
        get_policy: [:arn],
        get_policy_version: [:arn, :version_id],
        create_policy_version: [:arn],
        set_default_policy_version: [:arn, :version_id],
        delete_policy_version: [:arn, :version_id],
        list_policy_versions: [:arn],
        list_policies: [],
        delete_policy: [:arn],
        attach_role_policy: [:role, :policy_arn],
        detach_role_policy: [:role, :policy_arn],
        list_attached_role_policies: [:role],
        attach_user_policy: [:user, :policy_arn],
        detach_user_policy: [:user, :policy_arn],
        attach_group_policy: [:group, :policy_arn],
        detach_group_policy: [:group, :policy_arn],
        list_mfa_devices: [:username],
        update_assume_role_policy: [:role_name],
        put_role_policy: [:role_name, :policy_name],
        get_role_policy: [:role_name, :policy_name],
        delete_role_policy: [:role_name, :policy_name],
        list_role_policies: [:role_name],
        create_open_id_connect_provider: [:url],
        get_open_id_connect_provider: [:arn],
        list_open_id_connect_providers: [],
        get_account_summary: [],
        delete_open_id_connect_provider: [:arn],
        update_open_id_connect_provider_thumbprint: [:arn],
        add_client_id_to_open_id_connect_provider: [:arn],
        remove_client_id_from_open_id_connect_provider: [:arn]
      ]
  end
end
